# serverless.yml

# IMPORTANT! ap-southeast-2
# 
service: Restaurant

package:
  exclude:
    - data/*
    - local/*

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  memorySize: 1024
  region: ap-southeast-2
  timeout: 15
  versionFunctions: false  
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:*
    Resource:
      - "*"

functions:
  app:
    handler: index.handler
    events:
      - http: 
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
        
